/**
 * OpenFishTools Studio - Modular Effects Auto-Loader
 * Automatically generated by scripts/sync-effects.js
 * Total Registered Effect Files: 55
 * Backends: Common (2D), WebGL (wgl/), WebGPU (wgpu/)
 * DO NOT EDIT DIRECTLY. Add new effects into effects/wgl/ or effects/wgpu/ instead.
 */
(function() {
  const EFFECT_FILES = [
  "anamorphic_flare.js",
  "angle_control.js",
  "bevel.js",
  "camera_lens_blur.js",
  "checkbox_control.js",
  "color_balance.js",
  "color_control.js",
  "color_temperature.js",
  "colorize.js",
  "deep_glow.js",
  "drop_shadow.js",
  "expression_controls.js",
  "fast_box_blur.js",
  "fill.js",
  "glow_aura.js",
  "gradient_overlay.js",
  "grid.js",
  "haze_flare.js",
  "lumia.js",
  "oscillate.js",
  "point_control.js",
  "radio_waves.js",
  "rays.js",
  "rgb_split.js",
  "scanline.js",
  "slider_control.js",
  "solid_aura.js",
  "star_burst.js",
  "swing.js",
  "tile.js",
  "tint.js",
  "transform.js",
  "vignette.js",
  "wgl/brightness_contrast.js",
  "wgl/chromatic_aberration.js",
  "wgl/curve.js",
  "wgl/diffusion.js",
  "wgl/exposure_gamma.js",
  "wgl/fsmb.js",
  "wgl/grad_exposure.js",
  "wgl/highlight_shadow.js",
  "wgl/hue_shift.js",
  "wgl/invert.js",
  "wgl/mono.js",
  "wgl/optic_compensation.js",
  "wgl/saturation_vibrant.js",
  "wgl/sharpen.js",
  "wgl/shatter.js",
  "wgl/turbulent_displace.js",
  "wgl/unsharp_mask.js",
  "wgl/warp.js",
  "wgl/wave_warp.js",
  "wgpu/invert.js",
  "wgpu/turbulent_displace.js",
  "wgpu/wave_warp.js"
];

  if (typeof window !== 'undefined' && typeof document !== 'undefined') {
    window.FISH_EFFECTS_FILES = EFFECT_FILES;

    // Load scripts synchronously during initial DOM parsing
    if (document.readyState === 'loading') {
      EFFECT_FILES.forEach(function(file) {
        document.write('<script src="effects/' + file + '"><\/script>');
      });
    } else {
      // Fallback: asynchronous document head insertion if DOM already parsed
      EFFECT_FILES.forEach(function(file) {
        const s = document.createElement('script');
        s.src = 'effects/' + file;
        s.async = false;
        document.head.appendChild(s);
      });
    }
  }

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { EFFECT_FILES };
  }
})();
