/**
 * OpenFishTools Studio - Modular Effects Auto-Loader
 * Automatically generated by scripts/sync-effects.js
 * Total Registered Effects: 60
 * DO NOT EDIT DIRECTLY. Add new effects into effects/<id>.js instead.
 */
(function() {
  const EFFECT_FILES = [
  "anamorphic_flare.js",
  "angle_control.js",
  "bevel.js",
  "box_3d.js",
  "brightness_contrast.js",
  "camera_lens_blur.js",
  "checkbox_control.js",
  "chromatic_aberration.js",
  "color_balance.js",
  "color_control.js",
  "color_temperature.js",
  "colorize.js",
  "curve.js",
  "deep_glow.js",
  "diffusion.js",
  "drop_shadow.js",
  "exposure_gamma.js",
  "expression_controls.js",
  "extrude_3d.js",
  "fast_box_blur.js",
  "fill.js",
  "flicker.js",
  "fsmb.js",
  "glow_aura.js",
  "grad_exposure.js",
  "gradient_overlay.js",
  "grid.js",
  "haze_flare.js",
  "highlight_shadow.js",
  "hue_shift.js",
  "invert.js",
  "linear_wipe.js",
  "lumia.js",
  "mono.js",
  "optic_compensation.js",
  "oscillate.js",
  "point_control.js",
  "pyramid_3d.js",
  "radio_waves.js",
  "rays.js",
  "remove_bg.js",
  "rgb_split.js",
  "saturation_vibrant.js",
  "scanline.js",
  "shake.js",
  "sharpen.js",
  "shatter.js",
  "slider_control.js",
  "solid_aura.js",
  "sphere_3d.js",
  "star_burst.js",
  "swing.js",
  "tile.js",
  "tint.js",
  "transform.js",
  "turbulent_displace.js",
  "unsharp_mask.js",
  "vignette.js",
  "warp.js",
  "wave_warp.js"
];

  if (typeof window !== 'undefined' && typeof document !== 'undefined') {
    window.FISH_EFFECTS_FILES = EFFECT_FILES;

    // Load scripts synchronously during initial DOM parsing
    if (document.readyState === 'loading') {
      EFFECT_FILES.forEach(function(file) {
        document.write('<script src="effects/' + file + '"><\/script>');
      });
    } else {
      // Fallback: asynchronous document head insertion if DOM already parsed
      EFFECT_FILES.forEach(function(file) {
        const s = document.createElement('script');
        s.src = 'effects/' + file;
        s.async = false;
        document.head.appendChild(s);
      });
    }
  }

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { EFFECT_FILES };
  }
})();
