/**
 * OpenFishTools Studio - Modular Effects Runtime Auto-Loader
 *
 * Include this ONE script (after js/effects.js) instead of listing every effect in HTML.
 * Discovery order:
 *   1. /api/effects           live directory scan (dev server)  -> new files appear instantly
 *   2. effects/manifest.json  static manifest (static hosts, PWA, desktop builds)
 *   3. FALLBACK_FILES         list embedded below (generated by scripts/sync-effects.js)
 *
 * Add a new effect by dropping effects/<id>.js that calls FishEffectsRegistry.register({...}).
 * The embedded fallback list is generated - DO NOT EDIT DIRECTLY.
 * Fallback effect files: 62
 */
(function () {
  'use strict';

  var FALLBACK_FILES = [
  "anamorphic_flare.js",
  "angle_control.js",
  "bevel.js",
  "box_3d.js",
  "brightness_contrast.js",
  "camera_lens_blur.js",
  "checkbox_control.js",
  "chromatic_aberration.js",
  "color_balance.js",
  "color_control.js",
  "color_temperature.js",
  "colorize.js",
  "curve.js",
  "deep_glow.js",
  "diffusion.js",
  "drop_shadow.js",
  "exposure_gamma.js",
  "expression_controls.js",
  "extrude_3d.js",
  "fast_box_blur.js",
  "fill.js",
  "flicker.js",
  "fsmb.js",
  "glow_aura.js",
  "grad_exposure.js",
  "gradient_overlay.js",
  "grid.js",
  "haze_flare.js",
  "highlight_shadow.js",
  "hue_shift.js",
  "invert.js",
  "linear_wipe.js",
  "lumia.js",
  "mono.js",
  "optic_compensation.js",
  "oscillate.js",
  "particle_engine.js",
  "point_control.js",
  "pyramid_3d.js",
  "radio_waves.js",
  "rays.js",
  "remove_bg.js",
  "rgb_split.js",
  "saturation_vibrant.js",
  "scanline.js",
  "shake.js",
  "sharpen.js",
  "shatter.js",
  "slider_control.js",
  "solid_aura.js",
  "sphere_3d.js",
  "star_burst.js",
  "swing.js",
  "tile.js",
  "tint.js",
  "transform.js",
  "turbulent_displace.js",
  "unsharp_mask.js",
  "vignette.js",
  "warp.js",
  "wave_warp.js",
  "wipe_jaws.js"
];

  if (typeof window === 'undefined' || typeof document === 'undefined') {
    if (typeof module !== 'undefined' && module.exports) module.exports = { FALLBACK_FILES: FALLBACK_FILES };
    return;
  }

  function currentVersionQuery() {
    var script = document.currentScript;
    var src = script && script.src ? script.src : '';
    var m = /[?&]v=([^&#]+)/.exec(src);
    if (m) return '?v=' + m[1];
    if (window.OFT_VERSION) return '?v=' + encodeURIComponent(window.OFT_VERSION);
    return '';
  }

  function fetchJsonSync(url) {
    try {
      var xhr = new XMLHttpRequest();
      xhr.open('GET', url, false);
      xhr.setRequestHeader('Accept', 'application/json');
      xhr.send(null);
      if (xhr.status >= 200 && xhr.status < 300 && xhr.responseText) {
        return JSON.parse(xhr.responseText);
      }
    } catch (_) {}
    return null;
  }

  function filesFromManifest(manifest) {
    if (!Array.isArray(manifest)) return null;
    var seen = {};
    var out = [];
    manifest.forEach(function (item) {
      var f = typeof item === 'string' ? item : (item && item.file);
      if (f && /^[A-Za-z0-9_.-]+\.js$/.test(f) && !seen[f]) {
        seen[f] = true;
        out.push(f);
      }
    });
    out.sort();
    return out.length ? out : null;
  }

  var isHttp = /^https?:$/.test(window.location.protocol);
  var files = null;
  var source = 'fallback';

  if (isHttp) {
    files = filesFromManifest(fetchJsonSync('/api/effects'));
    if (files) source = 'api';
    if (!files) {
      files = filesFromManifest(fetchJsonSync('effects/manifest.json' + currentVersionQuery()));
      if (files) source = 'manifest';
    }
  }
  if (!files) files = FALLBACK_FILES.slice();

  window.FISH_EFFECTS_FILES = files;
  window.FISH_EFFECTS_SOURCE = source;

  var ver = currentVersionQuery();
  if (document.readyState === 'loading') {
    // Parser-blocking, in-order execution: effects are registered before editor scripts run
    files.forEach(function (file) {
      document.write('<script src="effects/' + file + ver + '"><\/script>');
    });
  } else {
    // Late load (script injected after parsing): keep order, the gallery listens for registrations
    files.forEach(function (file) {
      var s = document.createElement('script');
      s.src = 'effects/' + file + ver;
      s.async = false;
      document.head.appendChild(s);
    });
  }

  if (typeof module !== 'undefined' && module.exports) module.exports = { FALLBACK_FILES: files };
})();
