/**
 * OpenFishTools Studio - Automated Effects Synchronizer & Discovery
 * Recursively scans effects/, effects/wgl/, and effects/wgpu/
 * Synchronizes effects/loader.js & effects/manifest.json
 *
 * Usage:
 *   node scripts/sync-effects.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const EFFECTS_DIR = path.join(ROOT, 'effects');
const LOADER_PATH = path.join(EFFECTS_DIR, 'loader.js');
const MANIFEST_PATH = path.join(EFFECTS_DIR, 'manifest.json');

function collectEffectFiles(dir, prefix = '') {
  if (!fs.existsSync(dir)) return [];
  let list = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const ent of entries) {
    if (ent.name.startsWith('.') || ent.name === 'node_modules') continue;
    const relPath = prefix ? `${prefix}/${ent.name}` : ent.name;
    if (ent.isDirectory()) {
      list = list.concat(collectEffectFiles(path.join(dir, ent.name), relPath));
    } else if (ent.isFile() && ent.name.endsWith('.js') && ent.name !== 'loader.js' && ent.name !== 'index.js') {
      list.push(relPath);
    }
  }
  return list;
}

function syncEffects() {
  if (!fs.existsSync(EFFECTS_DIR)) return [];

  // Sort files with root/common first, then wgl, then wgpu
  const allFiles = collectEffectFiles(EFFECTS_DIR).sort((a, b) => {
    const order = (f) => {
      if (f.startsWith('wgpu/')) return 3;
      if (f.startsWith('wgl/')) return 2;
      return 1;
    };
    const diff = order(a) - order(b);
    if (diff !== 0) return diff;
    return a.localeCompare(b);
  });

  const manifestMap = new Map();

  allFiles.forEach(file => {
    try {
      const fullPath = path.join(EFFECTS_DIR, file);
      const code = fs.readFileSync(fullPath, 'utf8');
      const idMatch = code.match(/id:\s*['"]([^'"]+)['"]/) ||
                      code.match(/registerBackend\(\s*['"]([^'"]+)['"]/);
      const nameMatch = code.match(/name:\s*['"]([^'"]+)['"]/);
      const catMatch = code.match(/category:\s*['"]([^'"]+)['"]/);
      const iconMatch = code.match(/icon:\s*['"]([^'"]+)['"]/);

      const baseName = path.basename(file, '.js');
      const id = idMatch ? idMatch[1] : baseName;
      const name = nameMatch ? nameMatch[1] : id;
      const category = catMatch ? catMatch[1] : 'lightning';
      const icon = iconMatch ? iconMatch[1] : 'assets/FXPH.svg';

      let backend = 'common';
      if (file.startsWith('wgl/')) backend = 'wgl';
      else if (file.startsWith('wgpu/')) backend = 'wgpu';

      if (!manifestMap.has(id)) {
        manifestMap.set(id, {
          file,
          id,
          name,
          category,
          icon,
          backends: [backend],
          files: { [backend]: file }
        });
      } else {
        const item = manifestMap.get(id);
        if (!item.backends.includes(backend)) {
          item.backends.push(backend);
        }
        item.files[backend] = file;
        if (backend === 'wgl' && item.file.startsWith('wgpu/')) {
          item.file = file; // Prefer primary fallback as default file pointer
        }
      }
    } catch (e) {
      console.error(`[SyncEffects] Error reading ${file}:`, e);
    }
  });

  const manifest = Array.from(manifestMap.values()).sort((a, b) => a.name.localeCompare(b.name));

  // 1. Write effects/manifest.json
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  // 2. Write effects/loader.js
  const loaderContent = `/**
 * OpenFishTools Studio - Modular Effects Auto-Loader
 * Automatically generated by scripts/sync-effects.js
 * Total Registered Effect Files: ${allFiles.length}
 * Backends: Common (2D), WebGL (wgl/), WebGPU (wgpu/)
 * DO NOT EDIT DIRECTLY. Add new effects into effects/wgl/ or effects/wgpu/ instead.
 */
(function() {
  const EFFECT_FILES = ${JSON.stringify(allFiles, null, 2)};

  if (typeof window !== 'undefined' && typeof document !== 'undefined') {
    window.FISH_EFFECTS_FILES = EFFECT_FILES;

    // Load scripts synchronously during initial DOM parsing
    if (document.readyState === 'loading') {
      EFFECT_FILES.forEach(function(file) {
        document.write('<script src="effects/' + file + '"><\\/script>');
      });
    } else {
      // Fallback: asynchronous document head insertion if DOM already parsed
      EFFECT_FILES.forEach(function(file) {
        const s = document.createElement('script');
        s.src = 'effects/' + file;
        s.async = false;
        document.head.appendChild(s);
      });
    }
  }

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { EFFECT_FILES };
  }
})();
`;

  fs.writeFileSync(LOADER_PATH, loaderContent, 'utf8');
  console.log(`[SyncEffects] Successfully synchronized ${allFiles.length} effect files (${manifest.length} unique effects) to effects/loader.js and manifest.json`);
  return manifest;
}

if (require.main === module) {
  syncEffects();
}

module.exports = { syncEffects };
