/**
 * OpenFishTools Studio - Automated Effects Synchronizer & Discovery
 * Scans effects/ directory and synchronizes effects/loader.js & effects/manifest.json
 *
 * Usage:
 *   node scripts/sync-effects.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const EFFECTS_DIR = path.join(ROOT, 'effects');
const LOADER_PATH = path.join(EFFECTS_DIR, 'loader.js');
const MANIFEST_PATH = path.join(EFFECTS_DIR, 'manifest.json');

function syncEffects() {
  if (!fs.existsSync(EFFECTS_DIR)) return [];

  const files = fs.readdirSync(EFFECTS_DIR)
    .filter(f => f.endsWith('.js') && f !== 'loader.js' && f !== 'index.js' && !f.startsWith('.'))
    .sort();

  const manifest = [];

  files.forEach(file => {
    try {
      const code = fs.readFileSync(path.join(EFFECTS_DIR, file), 'utf8');
      const idMatch = code.match(/id:\s*['"]([^'"]+)['"]/);
      const nameMatch = code.match(/name:\s*['"]([^'"]+)['"]/);
      const catMatch = code.match(/category:\s*['"]([^'"]+)['"]/);
      const iconMatch = code.match(/icon:\s*['"]([^'"]+)['"]/);

      const id = idMatch ? idMatch[1] : file.replace(/\.js$/, '');
      const name = nameMatch ? nameMatch[1] : id;
      const category = catMatch ? catMatch[1] : 'lightning';
      const icon = iconMatch ? iconMatch[1] : 'assets/FXPH.svg';

      manifest.push({
        file,
        id,
        name,
        category,
        icon
      });
    } catch (e) {
      console.error(`[SyncEffects] Error reading ${file}:`, e);
    }
  });

  // 1. Write effects/manifest.json
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  // 2. Write effects/loader.js
  const loaderContent = `/**
 * OpenFishTools Studio - Modular Effects Auto-Loader
 * Automatically generated by scripts/sync-effects.js
 * Total Registered Effects: ${files.length}
 * DO NOT EDIT DIRECTLY. Add new effects into effects/<id>.js instead.
 */
(function() {
  const EFFECT_FILES = ${JSON.stringify(files, null, 2)};

  if (typeof window !== 'undefined' && typeof document !== 'undefined') {
    window.FISH_EFFECTS_FILES = EFFECT_FILES;

    // Load scripts synchronously during initial DOM parsing
    if (document.readyState === 'loading') {
      EFFECT_FILES.forEach(function(file) {
        document.write('<script src="effects/' + file + '"><\\/script>');
      });
    } else {
      // Fallback: asynchronous document head insertion if DOM already parsed
      EFFECT_FILES.forEach(function(file) {
        const s = document.createElement('script');
        s.src = 'effects/' + file;
        s.async = false;
        document.head.appendChild(s);
      });
    }
  }

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { EFFECT_FILES };
  }
})();
`;

  fs.writeFileSync(LOADER_PATH, loaderContent, 'utf8');

  // 3. Synchronize static script tags in editor.html and desktop.html
  let verParam = '';
  try {
    const vJson = JSON.parse(fs.readFileSync(path.join(ROOT, 'version.json'), 'utf8'));
    if (vJson && vJson.version) verParam = `?v=${vJson.version}`;
  } catch (_) {}
  const effectScriptsBlock = files.map(f => `  <script src="effects/${f}${verParam}"></script>`).join('\n');
  const htmlTargets = ['editor.html', 'desktop.html', 'demo.html'];
  const effectsBlockRegex = /(?:[ \t]*<script src="effects\/[^"]+"><\/script>\r?\n)+/;

  htmlTargets.forEach(relPath => {
    const fullPath = path.join(ROOT, relPath);
    if (!fs.existsSync(fullPath)) return;
    try {
      const origContent = fs.readFileSync(fullPath, 'utf8');
      if (effectsBlockRegex.test(origContent)) {
        const newContent = origContent.replace(effectsBlockRegex, effectScriptsBlock + '\n');

        // Strict integrity guard: abort if content shrank unexpectedly or lost closing tags
        if (newContent.length < origContent.length * 0.90 || !newContent.includes('</html>')) {
          throw new Error(`Integrity check failed: content size shrank from ${origContent.length} to ${newContent.length}`);
        }

        // Atomic write via temp file to avoid buffer corruption
        const tmpPath = fullPath + '.tmp.' + Date.now() + Math.random().toString(36).substring(2, 6);
        fs.writeFileSync(tmpPath, newContent, 'utf8');
        fs.renameSync(tmpPath, fullPath);
        console.log(`[SyncEffects] Synchronized ${files.length} effect scripts in ${relPath}`);
      }
    } catch (err) {
      console.error(`[SyncEffects] Error synchronizing ${relPath}:`, err);
    }
  });

  console.log(`[SyncEffects] Successfully synchronized ${files.length} effects to effects/loader.js, manifest.json, and HTML templates`);
  return manifest;
}

if (require.main === module) {
  syncEffects();
}

module.exports = { syncEffects };
